import { x } from "./commands/x.js";
import { conversation } from "./commands/conversation.js";
import { list as listConversations } from "./commands/conversation/list.js";
import { listen as listenForConversations } from "./commands/conversation/listen.js";
import { create as createConversation } from "./commands/conversation/create.js";
import { send } from "./commands/conversation/send.js";
import { group } from "./commands/group.js";
import { create } from "./commands/group/admin/create.js";
import { describe } from "./commands/group/admin/describe.js";
import { del } from "./commands/group/admin/del.js";
import { list as listGroups } from "./commands/group/admin/list.js";
import { invite } from "./commands/group/admin/invite.js";
import { join } from "./commands/group/member/join.js";
import { decline } from "./commands/group/member/decline.js";
import { leave } from "./commands/group/member/leave.js";
import { kick } from "./commands/group/admin/kick.js";

group.addCommand(create);
group.addCommand(describe);
group.addCommand(del);
group.addCommand(listGroups);
group.addCommand(invite);
group.addCommand(decline);
group.addCommand(kick);
group.addCommand(join);
group.addCommand(leave);
x.addCommand(group);
conversation.addCommand(listConversations);
conversation.addCommand(listenForConversations);
conversation.addCommand(createConversation);
conversation.addCommand(send);
x.addCommand(conversation);
x.parse();
